name: "Hassfest and hacs validation"
on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: home-assistant/actions/hassfest@master
      - uses: hacs/action@main
        with:
          category: integration
